squid:
  image: sameersbn/squid:latest
  ports:
   - "3128:3128"
  links:
   - web
  volumes_from:
   - squidlogvolume

squidlogvolume:
  image: busybox:latest
  volumes:
   - /var/log/squid3

squidaccesslog:
  image: busybox:latest
  volumes_from:
   - squidlogvolume
  command: sh -c 'touch /var/log/squid3/access.log ; tail -f /var/log/squid3/access.log'

squidcachelog:
  image: busybox:latest
  volumes_from:
   - squidlogvolume
  command: sh -c 'touch /var/log/squid3/cache.log ; tail -f /var/log/squid3/cache.log'

web:
  build: .
  ports:
   - "5000:5000"
  volumes:
  - .:/code
