squid:
  image: sameersbn/squid:latest
  ports:
   - "3128:3128"
  links:
   - varnish
  volumes_from:
   - squidlogvolume
  command: bash -c 'echo "debug_options ALL,1" >>/etc/squid3/squid.conf ; tail /etc/squid3/squid.conf ; /start'

squidlogvolume:
  image: busybox:latest
  volumes:
   - /var/log/squid3

squidaccesslog:
  image: busybox:latest
  volumes_from:
   - squidlogvolume
  command: sh -c 'touch /var/log/squid3/access.log ; tail -f /var/log/squid3/access.log'

squidcachelog:
  image: busybox:latest
  volumes_from:
   - squidlogvolume
  command: sh -c 'touch /var/log/squid3/cache.log ; tail -f /var/log/squid3/cache.log'

varnish:
  image: million12/varnish:latest
  links:
   - web
  volumes_from:
   - web
  ports:
   - "80:80"
  environment:
   - VCL_CONFIG=/code/varnish.vcl
#   - VARNISHD_PARAMS=""
#  command: varnishd -d -u varnish -f /code/varnish.vcl -s malloc,64m

web:
  build: .
  ports:
   - "5000:5000"
  volumes:
  - .:/code
